"""Generate The AI SDLC Map site from content/.

Source of truth:
  content/toc.yml            site identity, and the series parts this site links to
  content/glossary.yml       terms, attribution, sources, auto-link phrases
  content/references.yml     canonical references
  content/workflows/catalog.yml   the SDLC workflow catalog
  content/diagrams/svg/*.svg      diagram sources (the map ones generated by content/diagrams/map/build_map.py)

Output: site/ (static HTML, inline SVG, one CSS file, one JS file).
Run:    python site/generate.py
"""
from __future__ import annotations

import html
import importlib.util
import json
import math
import re
import sys
import xml.etree.ElementTree as ET
from datetime import date
from pathlib import Path

import markdown
import yaml

ROOT = Path(__file__).resolve().parents[1]
CONTENT = ROOT / "content"
SITE = ROOT / "site"
DIAGRAMS_SVG = CONTENT / "diagrams" / "svg"
OUT_DIAGRAMS = SITE / "diagrams"

TOC = yaml.safe_load((CONTENT / "toc.yml").read_text(encoding="utf-8"))
GLOSSARY = yaml.safe_load((CONTENT / "glossary.yml").read_text(encoding="utf-8"))
REFERENCES = yaml.safe_load((CONTENT / "references.yml").read_text(encoding="utf-8"))
CATALOG = yaml.safe_load((CONTENT / "workflows" / "catalog.yml").read_text(encoding="utf-8"))
VERSION = (CONTENT / "VERSION").read_text(encoding="utf-8").strip()
CHANGELOG = (CONTENT / "CHANGELOG.md").read_text(encoding="utf-8")

SITE_URL = TOC["site_url"].rstrip("/")
TITLE = TOC["title"]
SERIES = TOC["series"]
SERIES_URL = SERIES["url"].rstrip("/")
PARTS = SERIES["parts"]
PART_BY_ID = {c["id"]: c for c in PARTS}
TODAY = date.today().isoformat()

GLOSS_BY_ID = {g["id"]: g for g in GLOSSARY}


def part_url(part: dict) -> str:
    """Parts of the series live on the series site, not here."""
    return f"{SERIES_URL}/{part['slug']}.html"


def part_chip(part: dict) -> str:
    return f'<a class="chip" href="{esc(part_url(part))}" rel="noopener">Part {part["number"]}</a>'


def esc(s) -> str:
    return html.escape(str(s), quote=True)


def read(p: Path) -> str:
    return p.read_text(encoding="utf-8")


def write(p: Path, s: str) -> None:
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(s, encoding="utf-8")


# --------------------------------------------------------------------------- diagrams
def svg_source(diagram_id: str, instance: str, markup: str | None = None) -> tuple[str, int, int]:
    """Return (svg markup, width, height) for a diagram id, or for the given markup of that diagram."""
    p = DIAGRAMS_SVG / f"{diagram_id}.svg"
    if markup is not None:
        svg = markup
    elif p.exists():
        svg = read(p)
    else:
        raise SystemExit(f"Unknown diagram: {diagram_id}")
    m = re.search(r'<svg[^>]*width="(\d+)"[^>]*height="(\d+)"', svg)
    w, h = (int(m.group(1)), int(m.group(2))) if m else (1200, 628)
    # Namespace definitions per occurrence, including repeats.
    id_map = {old: f"{instance}-{old}" for old in re.findall(r'\bid="([^"]+)"', svg)}
    svg = re.sub(r'\bid="([^"]+)"', lambda m: f'id="{id_map[m.group(1)]}"', svg)
    svg = re.sub(r'url\(#([^)]+)\)', lambda m: f'url(#{id_map.get(m.group(1), m.group(1))})', svg)
    svg = re.sub(r'((?:xlink:)?href=")#([^"]+)(")',
                 lambda m: m.group(1) + '#' + id_map.get(m.group(2), m.group(2)) + m.group(3), svg)
    # scope the style rules to this svg only
    svg = re.sub(r"<style>(.*?)</style>", lambda mm: "<style>" + scope_css(mm.group(1), instance) + "</style>", svg, flags=re.S)
    # A diagram with links is a group, not an image: children of role="img" are presentational,
    # which can hide the links from assistive technology.
    role = "group" if "<a " in svg else "img"
    svg = svg.replace("<svg ", f'<svg id="svg-{instance}" role="{role}" aria-labelledby="cap-{instance}" ', 1)
    return svg, w, h


def scope_css(css: str, scope: str) -> str:
    out = []
    for rule in re.findall(r"([^{}]+)\{([^{}]*)\}", css):
        selectors, body = rule
        sels = []
        for sel in selectors.split(","):
            sel = sel.strip()
            if not sel or sel == "body":
                continue
            sels.append(f"#svg-{scope} {sel}")
        if sels:
            out.append(",".join(sels) + "{" + body + "}")
    return "".join(out)


def write_diagram_files() -> list[str]:
    """Write every diagram as a standalone .svg into site/diagrams (PNG rendering is scripts/render_diagrams.py)."""
    OUT_DIAGRAMS.mkdir(parents=True, exist_ok=True)
    ids = []
    for p in sorted(DIAGRAMS_SVG.glob("*.svg")):
        write(OUT_DIAGRAMS / p.name, read(p))
        ids.append(p.stem)
    return ids


def figure(diagram_id: str, caption: str, number: int | None = None, cls: str = "", markup: str | None = None) -> str:
    count = _FIGURE_COUNTS.get(diagram_id, 0) + 1
    _FIGURE_COUNTS[diagram_id] = count
    instance = f"{diagram_id}-{count}"
    svg, w, h = svg_source(diagram_id, instance, markup)
    label = f"Figure {number}. " if number else ""
    return (
        f'<figure class="diagram {cls}" data-diagram="{diagram_id}" style="--ar:{w}/{h}">'
        f'<div class="diagram-frame"><button class="zoom" type="button" aria-label="Open diagram full size" data-zoom="{diagram_id}">⤢</button>{svg}</div>'
        f'<figcaption id="cap-{instance}"><span class="fig-label">{label}</span>{esc(caption)}'
        f' <span class="fig-links"><a href="{rel("diagrams/" + diagram_id + ".svg")}" download>SVG</a> · <a href="{rel("diagrams/" + diagram_id + ".png")}" download>PNG</a></span></figcaption>'
        f"</figure>"
    )


# --------------------------------------------------------------------------- paths
_PREFIX = ""
_FIGURE_COUNTS: dict[str, int] = {}


def set_prefix(p: str) -> None:
    global _PREFIX
    _PREFIX = p
    _FIGURE_COUNTS.clear()


def rel(path: str) -> str:
    return _PREFIX + path


# --------------------------------------------------------------------------- markdown
MD_EXT = ["extra", "toc", "sane_lists", "codehilite"]
MD_CFG = {"toc": {"toc_depth": "2-3", "permalink": False}, "codehilite": {"guess_lang": False, "css_class": "hl"}}


def ref_footnote(key: str) -> str:
    r = REFERENCES[key]
    bits = [f"<strong>{esc(r['title'])}</strong>"]
    who = ", ".join(x for x in [r.get("author"), r.get("org")] if x)
    if who:
        bits.append(esc(who))
    if r.get("date"):
        bits.append(esc(r["date"]))
    line = " — ".join(bits)
    if r.get("url"):
        line += f' · <a href="{esc(r["url"])}" rel="noopener">source</a>'
    if r.get("note"):
        line += f" <span class=\"ref-note\">{esc(r['note'])}</span>"
    return line


def preprocess_markdown(md: str, chapter_id: str) -> tuple[str, list[str], list[str]]:
    """Resolve diagram embeds and add reference footnote definitions.

    Returns (markdown, diagram ids used in order, footnote keys used).
    """
    diagrams: list[str] = []

    def fig_sub(m: re.Match) -> str:
        diagrams.append(m.group(2))
        n = len(diagrams)
        return f"\n\n<!--FIG:{m.group(2)}|{n}|{m.group(1)}-->\n\n"

    md = re.sub(r"!\[([^\]]*)\]\(diagram:([a-z0-9\-]+)\)", fig_sub, md)
    used = sorted(set(re.findall(r"\[\^([a-z0-9\-]+)\](?!:)", md)))
    defined = set(re.findall(r"^\[\^([a-z0-9\-]+)\]:", md, flags=re.M))
    overrides = defined & REFERENCES.keys()
    if overrides:
        raise SystemExit(f"{chapter_id}: canonical reference keys cannot be redefined locally: {', '.join(sorted(overrides))}")
    extra = []
    for key in used:
        if key in defined:
            continue
        if key not in REFERENCES:
            raise SystemExit(f"{chapter_id}: footnote [^{key}] has no definition and is not in references.yml")
        extra.append(f"[^{key}]: {ref_footnote(key)}")
    if extra:
        md += "\n\n" + "\n".join(extra) + "\n"
    return md, diagrams, used


def render_markdown(md: str) -> tuple[str, list[dict]]:
    m = markdown.Markdown(extensions=MD_EXT, extension_configs=MD_CFG)
    body = m.convert(md)
    toc = [t for t in m.toc_tokens if t["level"] == 2] if hasattr(m, "toc_tokens") else []
    return body, toc


def autolink_terms(body: str, chapter_id: str) -> tuple[str, list[str]]:
    """Link the first occurrence of each glossary phrase in the running prose."""
    linked: list[str] = []
    # split into segments we may touch (text nodes outside tags/headings/links/code)
    protected = re.compile(r"(<(?:h[1-6]|a|code|pre|figure|sup|strong)\b[^>]*>.*?</(?:h[1-6]|a|code|pre|figure|sup|strong)>|<[^>]+>)", re.S)
    parts = protected.split(body)
    for g in GLOSSARY:
        phrases = g.get("match") or []
        if not phrases:
            continue
        done = False
        for i, part in enumerate(parts):
            if done or not part or part.startswith("<"):
                continue
            for phrase in phrases:
                pat = re.compile(r"(?<![\w-])(" + re.escape(phrase) + r")(?![\w-])")
                if pat.search(part):
                    parts[i] = pat.sub(
                        lambda mm: f'<a class="term" href="{rel("glossary.html")}#{g["id"]}" data-term="{g["id"]}">{mm.group(1)}</a>',
                        part, count=1)
                    linked.append(g["id"])
                    done = True
                    break
    return "".join(parts), linked


# --------------------------------------------------------------------------- page chrome
def head(title: str, description: str, path: str, og_image: str = "og-image.png", extra: str = "") -> str:
    canonical = f"{SITE_URL}/{path}" if path != "index.html" else f"{SITE_URL}/"
    return f"""<!DOCTYPE html>
<html lang="en" data-theme="auto">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{esc(title)}</title>
<meta name="description" content="{esc(description)}">
<link rel="canonical" href="{canonical}">
<meta property="og:type" content="article">
<meta property="og:title" content="{esc(title)}">
<meta property="og:description" content="{esc(description)}">
<meta property="og:image" content="{SITE_URL}/{og_image}">
<meta property="og:url" content="{canonical}">
<meta name="twitter:card" content="summary_large_image">
<meta name="theme-color" content="#f6f4ee" media="(prefers-color-scheme: light)">
<meta name="theme-color" content="#14130f" media="(prefers-color-scheme: dark)">
<link rel="icon" href="{rel('favicon.svg')}" type="image/svg+xml">
<link rel="stylesheet" href="{rel('assets/style.css')}?v={VERSION}">
<script>try{{const t=localStorage.getItem('bfc-theme');if(t)document.documentElement.dataset.theme=t;}}catch(e){{}}</script>
{extra}
</head>
"""


def nav(current: str = "") -> str:
    def item(href: str, label: str, key: str) -> str:
        cls = ' class="on"' if key == current else ""
        return f'<a href="{rel(href)}"{cls}>{label}</a>'

    return f"""<header class="topbar">
<div class="topbar-inner">
<a class="brand" href="{rel('index.html')}"><span class="brand-mark" aria-hidden="true"></span><span>{esc(TITLE)}</span></a>
<nav class="topnav" aria-label="Site">
{item('index.html#map', 'Map', 'home')}
{item('workflow-catalog.html', 'Workflow catalog', 'workflows')}
{item('glossary.html', 'Terminology', 'glossary')}
{item('references.html', 'References', 'references')}
<a href="{esc(SERIES_URL)}/" rel="noopener">Series</a>
<button class="iconbtn" id="search-open" type="button" aria-label="Search (press /)"><svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="11" cy="11" r="7"/><path d="m20 20-3.5-3.5"/></svg></button>
<button class="iconbtn" id="theme-toggle" type="button" aria-label="Toggle colour theme"><svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M12 3a9 9 0 1 0 9 9c0-.5 0-1-.1-1.4A5.5 5.5 0 0 1 12 3z"/></svg></button>
<button class="iconbtn menu" id="menu-toggle" type="button" aria-label="Menu" aria-expanded="false"><svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M4 7h16M4 12h16M4 17h16"/></svg></button>
</nav>
</div>
<div class="progress" id="progress" aria-hidden="true"><span></span></div>
</header>
"""


def footer() -> str:
    return f"""<footer class="footer">
<div class="footer-inner">
<div>
<div class="footer-title">{esc(TITLE)}</div>
<div class="muted">By <a href="{esc(TOC['author_url'])}" rel="noopener">{esc(TOC['author'])}</a>, companion to the series <a href="{esc(SERIES_URL)}/" rel="noopener">{esc(SERIES['title'])}</a>. Edition {esc(VERSION)}. Prose <a href="https://creativecommons.org/licenses/by/4.0/" rel="noopener">CC BY 4.0</a>; site tooling MIT.</div>
</div>
<div class="footer-links">
<a href="{rel('index.html#map')}">Map</a>
<a href="{rel('workflow-catalog.html')}">Workflow catalog</a>
<a href="{rel('glossary.html')}">Terminology</a>
<a href="{rel('references.html')}">References</a>
<a href="{esc(SERIES_URL)}/" rel="noopener">Series</a>
<a href="{esc(TOC['repo_url'])}" rel="noopener">Source</a>
<a href="{rel('llms.txt')}">llms.txt</a>
</div>
</div>
</footer>
<div class="lightbox" id="lightbox" hidden><button class="lightbox-close" type="button" aria-label="Close">×</button><div class="lightbox-body"></div></div>
<div class="search" id="search" hidden><div class="search-box"><input id="search-input" type="search" placeholder="Search terms and workflows…" autocomplete="off"><div id="search-results" class="search-results"></div><div class="search-hint">Type to search terms, workflows and the series parts. <kbd>Esc</kbd> closes.</div></div></div>
<div class="tip" id="tip" role="tooltip" hidden></div>
<script src="{rel('assets/app.js')}?v={VERSION}"></script>
"""


def glossary_json() -> str:
    data = {g["id"]: {"term": g["term"], "def": g["definition"].strip(), "attr": g["attribution"], "src": g.get("source")} for g in GLOSSARY}
    return f'<script id="glossary-data" type="application/json">{json.dumps(data)}</script>'


# --------------------------------------------------------------------------- clickable map
def linked_map() -> str:
    """The map with every label in content/diagrams/map/links.yml turned into a link.

    Fails the build if a listed label is not on the map, or a series target names no part.
    Relative targets are checked by the site tests' link check.
    """
    spec = importlib.util.spec_from_file_location("build_map", CONTENT / "diagrams" / "map" / "build_map.py")
    build_map = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(build_map)  # type: ignore[union-attr]
    links = yaml.safe_load((CONTENT / "diagrams" / "map" / "links.yml").read_text(encoding="utf-8"))
    hrefs = {}
    for label, target in links.items():
        if target.startswith("series:"):
            part = PART_BY_ID.get(target.split(":", 1)[1])
            if not part:
                raise SystemExit(f"links.yml: '{label}' points at {target}, which is not a series part")
            hrefs[label] = part_url(part)
        else:
            hrefs[label] = target
    svg = build_map.page_map(hrefs)
    missing = sorted(set(hrefs) - build_map.LINKED)
    if missing:
        raise SystemExit(f"links.yml: labels not on the map: {missing}")
    return svg


# --------------------------------------------------------------------------- home
def routes() -> str:
    """The purpose routing row under the map (project/APPROACH.md): only destinations that exist."""
    p = PART_BY_ID
    rows = [
        ("Understand", "What changes when agents do more of the delivery work, and the words for it.",
         [(part_url(p["part-1"]), f"The series, from Part 1", True), ("glossary.html", "Terminology and sources", False)]),
        ("Build the kit", "The engineering environment the agent works in: rules, checks, skills and evidence.",
         [(part_url(p["part-3"]), "Harness engineering (Part 3)", True), (part_url(p["part-4"]), "The Engineering Kit (Part 4)", True)]),
        ("Run a workflow", "One delivery decision end to end, with a trigger, checks, a human decision and evidence.",
         [("workflow-catalog.html", f"{len(CATALOG['workflows'])} workflows in the catalog", False), (part_url(p["part-7"]), "One workflow in full (Part 7)", True)]),
        ("Lead adoption", "What to build first, what to measure, and when to move on.",
         [("#adoption", "The adoption path", False), (part_url(p["part-6"]), "The software factory (Part 6)", True)]),
        ("Look it up", "Definitions, sources and the catalog as data.",
         [("glossary.html", "Terminology", False), ("references.html", "References", False), ("data/workflow-catalog.csv", "Catalog as CSV", False)]),
    ]
    out = ""
    for title, blurb, links in rows:
        noopener = ' rel="noopener"'
        items = "".join(f'<li><a href="{esc(h)}"{noopener if ext else ""}>{esc(label)}</a></li>' for h, label, ext in links)
        out += f'<div class="route"><h3>{esc(title)}</h3><p>{esc(blurb)}</p><ul>{items}</ul></div>'
    return out


def render_index() -> str:
    set_prefix("")
    n_workflows = len(CATALOG["workflows"])
    n_terms = len(GLOSSARY)
    parts = "".join(
        f'<li><a href="{esc(part_url(c))}" rel="noopener"><span class="layer-k">Part {c["number"]}</span> {esc(c["title"])}</a></li>'
        for c in PARTS)
    page = head(f"{TITLE} — the AI-assisted software lifecycle on one page", TOC["about"], "index.html", "diagrams/ai-sdlc-map.png")
    page += "<body class=\"home\">" + nav("home")
    page += f"""
<main>
<section class="hero hero-plain">
<div class="hero-inner">
<div class="kicker">Reference · edition {esc(VERSION)}</div>
<h1>The AI SDLC <em>Map</em></h1>
<p class="lede">{esc(TOC['tagline'])}</p>
<p class="hero-about">{esc(TOC['about'])}</p>
<div class="hero-actions"><a class="btn primary" href="#map">See the map</a><a class="btn" href="workflow-catalog.html">Browse the workflow catalog</a></div>
<div class="stats"><div><b>5</b><span>bands</span></div><div><b>5</b><span>adoption stages</span></div><div><b>{n_workflows}</b><span>catalogued workflows</span></div><div><b>{n_terms}</b><span>terms, each with its origin</span></div></div>
</div>
</section>

<section class="section" id="map">
<div class="section-inner">
<div class="section-head"><h2>The map</h2><p>Context sets the risk tier; the lifecycle says where the work runs; the core does the work; enablement makes it possible; assurance proves it. Underlined labels open the page that covers them; or start by purpose below the map.</p></div>
{figure('ai-sdlc-map', 'The AI SDLC Map: five bands and the adoption path. Underlined labels are links to the page that covers them.', None, 'clickable', linked_map())}
<nav class="routes" aria-label="Start by purpose">{routes()}</nav>
</div>
</section>

<section class="section alt" id="adoption">
<div class="section-inner">
<div class="section-head"><h2>The adoption path</h2><p>One step at a time, one workflow at a time. Each stage has something to build, something to measure, and a condition for moving on.</p></div>
{figure('ai-sdlc-adoption-path', 'Adoption path: from the deterministic floor to the software factory.')}
</div>
</section>

<section class="section" id="more">
<div class="section-inner">
<div class="section-head"><h2>Go further</h2><p>The map is the summary. These carry the detail.</p></div>
<div class="cards three">
<a class="card" href="workflow-catalog.html"><div class="card-num">Catalog</div><h3>{n_workflows} SDLC workflows, mapped to what they replace</h3><p>Every candidate workflow across the lifecycle, each with its decision, trigger, agent task, checks, human decision and evidence record, mapped one-to-one to the traditional activity it absorbs.</p></a>
<a class="card" href="glossary.html"><div class="card-num">Terminology</div><h3>Every term, and where it comes from</h3><p>Which words are adopted from Böckeler and Thoughtworks, which are adapted, and which were coined in the series, with a translation table between the vocabularies.</p></a>
<a class="card" href="references.html"><div class="card-num">References</div><h3>Every source in one place</h3><p>The public sources behind the terms, the map and the series, each with its author, publisher and link.</p></a>
</div>
<div class="section-head series-list"><h2>The series</h2><p><a href="{esc(SERIES_URL)}/" rel="noopener">{esc(SERIES['title'])}</a> is the narrative introduction. {esc(SERIES['summary'])}</p></div>
<ol class="parts-list">{parts}</ol>
</div>
</section>
</main>
{glossary_json()}
{footer()}
</body></html>"""
    return page


# --------------------------------------------------------------------------- glossary
ATTR_LABEL = {"adopted": "Adopted from source", "adapted": "Adapted from source", "coined": "Coined in the series", "common": "Common engineering usage"}


def render_glossary() -> str:
    set_prefix("")
    groups = {"adopted": [], "adapted": [], "coined": [], "common": []}
    for g in GLOSSARY:
        groups[g["attribution"]].append(g)
    items = ""
    for g in GLOSSARY:
        src = g.get("source")
        srcs = [src] + list(g.get("also") or []) if src else list(g.get("also") or [])
        authors = [REFERENCES[k].get("author") for k in srcs]
        # Name a source by its author; add the title when the same author is cited twice here.
        src_html = " ".join(
            f'<a class="src" href="references.html#{k}">{esc(a if a and authors.count(a) == 1 else ((a + ": ") if a else "") + REFERENCES[k]["title"])}</a>'
            for k, a in zip(srcs, authors))
        chapters = " ".join(part_chip(PART_BY_ID[c]) for c in g.get("chapters", []) if c in PART_BY_ID)
        counterpart = f'<div class="counterpart"><span class="k">In Böckeler\'s terms</span> {esc(g["counterpart"])}</div>' if g.get("counterpart") else ""
        items += f"""
<article class="term-entry" id="{g['id']}" data-attr="{g['attribution']}">
<div class="term-head"><h3>{esc(g['term'])}</h3><span class="attr attr-{g['attribution']}">{ATTR_LABEL[g['attribution']]}</span></div>
<p>{esc(g['definition'].strip())}</p>
{counterpart}
<div class="term-foot">{('<span class="k">Source</span> ' + src_html) if src_html else ''} {('<span class="k">Used in the series</span> ' + chapters) if chapters else ''}</div>
</article>"""

    translation = [
        ("Harness", "Harness (wide sense: the whole engineering environment)", "adopted"),
        ("Guides (feedforward controls)", "Skills, constitution, readiness questions", "adapted"),
        ("Sensors (feedback controls)", "Validators, tests, review skill", "adapted"),
        ("Computational controls", "Deterministic machinery; validators; gates", "adapted"),
        ("Inferential controls", "Probabilistic machinery; the review skill; harness evaluations", "adapted"),
        ("Regulation categories (maintainability, architecture, behaviour)", "Not used as categories; rules carry a route instead (gate / judgment / guidance)", "different"),
        ("Steering loop", "Feedback path, with its conversions named", "adapted"),
        ("Harnessability", "Give the agent a usable starting point; brownfield pre-flight analysis", "adapted"),
        ("Ambient affordances", "Not used; closest is the kit's technology profile", "different"),
        ("Harness templates", "Engineering Kit technology profiles", "adapted"),
        ("—", "Rule registry, evidence record, could_not_run, risk tier, workflow, software factory", "coined"),
    ]
    trans_html = "".join(f'<tr><td>{esc(a)}</td><td>{esc(b)}</td><td><span class="attr attr-{c}">{c}</span></td></tr>' for a, b, c in translation)

    page = head(f"Terminology and sources · {TITLE}", "Every term the map and the series use, what it means, and where it comes from: adopted from Böckeler and Thoughtworks, adapted, or coined in this work.", "glossary.html")
    page += "<body>" + nav("glossary")
    page += f"""
<main>
<div class="hero hero-plain"><div class="hero-inner"><div class="crumbs"><a href="index.html">{esc(TITLE)}</a> <span>/</span> Terminology</div><h1>Terminology and sources</h1>
<p class="lede">The map and the <a href="{esc(SERIES_URL)}/" rel="noopener">{esc(SERIES['title'])}</a> series reuse vocabulary that Birgitta Böckeler set out in <a href="https://martinfowler.com/articles/harness-engineering.html" rel="noopener">Harness Engineering for Coding Agent Users</a> on martinfowler.com, add a few working names of their own, and lean on ordinary engineering words for the rest. This page says which is which, so a reader moving between the two vocabularies can translate.</p>
<div class="filterbar" id="term-filter"><button class="chipbtn on" data-attr="all">All ({len(GLOSSARY)})</button>{''.join(f'<button class="chipbtn" data-attr="{k}">{ATTR_LABEL[k]} ({len(v)})</button>' for k, v in groups.items())}</div>
</div></div>
<div class="section-inner narrow">
<section class="translation">
<h2>Translation table</h2>
<p class="muted">Böckeler's vocabulary on the left, the vocabulary used here on the right. "Adapted" means the idea is hers and the word or scope is different here.</p>
<table class="table"><thead><tr><th>Böckeler / Thoughtworks</th><th>Used here</th><th>Relation</th></tr></thead><tbody>{trans_html}</tbody></table>
</section>
<section class="terms" id="terms">{items}</section>
</div>
</main>
{glossary_json()}
{footer()}
</body></html>"""
    return page


# --------------------------------------------------------------------------- references
def render_references() -> str:
    set_prefix("")
    used_by: dict[str, list[dict]] = {k: [] for k in REFERENCES}
    for part in PARTS:
        for k in part.get("cites") or []:
            if k in used_by:
                used_by[k].append(part)
    for g in GLOSSARY:
        for k in [g.get("source")] + list(g.get("also") or []):
            if k:
                used_by.setdefault(k, [])
    by_diagram: dict[str, list[tuple[str, str]]] = {}
    for p in sorted(DIAGRAMS_SVG.glob("*.svg")):
        svg = ET.parse(p).getroot()
        keys = set((svg.get("data-references") or "").split())
        for el in svg.iter():
            if "credit" in (el.get("class") or "").split():
                keys.update((el.get("data-references") or "").split())
        title = next((el.text for el in svg if el.tag.rsplit("}", 1)[-1] == "title" and el.text), p.stem)
        for k in keys:
            by_diagram.setdefault(k, []).append((p.stem, title))
    items = ""
    for k, r in REFERENCES.items():
        diags = " ".join(f'<a class="chip" href="diagrams/{stem}.svg">{esc(title)}</a>' for stem, title in by_diagram.get(k, []))
        chs = " ".join(part_chip(c) for c in used_by.get(k, []))
        terms = " ".join(f'<a class="chip" href="glossary.html#{g["id"]}">{esc(g["term"])}</a>' for g in GLOSSARY if k in ([g.get("source")] + list(g.get("also") or [])))
        items += f"""
<article class="ref-entry" id="{k}">
<h3><a href="{esc(r['url'])}" rel="noopener">{esc(r['title'])}</a></h3>
<div class="muted">{esc(', '.join(x for x in [r.get('author'), r.get('org')] if x))}{(' · ' + esc(r['date'])) if r.get('date') else ''}</div>
<p>{esc(r.get('note', ''))}</p>
<div class="term-foot">{('<span class="k">Cited in the series</span> ' + chs) if chs else ''} {('<span class="k">Terms</span> ' + terms) if terms else ''} {('<span class="k">Diagrams</span> ' + diags) if diags else ''}</div>
</article>"""
    page = head(f"References · {TITLE}", "Canonical list of the sources the map, the terminology and the series cite.", "references.html")
    page += "<body>" + nav("references")
    page += f"""
<main>
<div class="hero hero-plain"><div class="hero-inner"><div class="crumbs"><a href="index.html">{esc(TITLE)}</a> <span>/</span> References</div><h1>References</h1>
<p class="lede">Every source in one place. Each glossary term that is adopted or adapted names one of these, each downloadable diagram lists the sources it draws on, and each part of the <a href="{esc(SERIES_URL)}/" rel="noopener">{esc(SERIES['title'])}</a> series is listed against the sources it cites.</p></div></div>
<div class="section-inner narrow"><section class="refs">{items}</section></div>
</main>
{glossary_json()}
{footer()}
</body></html>"""
    return page


# --------------------------------------------------------------------------- workflow catalog
def render_catalog() -> str:
    set_prefix("")
    data = CATALOG
    phases = {p["key"]: p["name"] for p in data["phases"]}
    definition = PART_BY_ID["part-5"]
    wf_json = json.dumps({"phases": data["phases"], "maturity": data["maturity"], "sources": data["sources"], "workflows": data["workflows"], "traditional_map": data["traditional_map"],
                          "definition": {"url": part_url(definition), "label": f"How workflows are defined (Part {definition['number']})"}})
    counts = {}
    for w in data["workflows"]:
        counts[w["maturity"]] = counts.get(w["maturity"], 0) + 1
    page = head(f"SDLC workflow catalog · {TITLE}", f"{len(data['workflows'])} candidate workflows across the software lifecycle, each mapped to the traditional activity it absorbs, with its activities split into agent, checks and people.", "workflow-catalog.html")
    page += "<body>" + nav("workflows")
    page += f"""
<main>
<div class="hero hero-plain"><div class="hero-inner"><div class="crumbs"><a href="index.html">{esc(TITLE)}</a> <span>/</span> Workflow catalog</div><h1>SDLC workflow catalog</h1>
<p class="lede">Every candidate workflow across the software development lifecycle (SDLC), using the definition from <a href="{esc(part_url(definition))}" rel="noopener">Part {definition['number']} of the series</a>: it supports one delivery decision; it has a trigger, an agent action, deterministic checks, a human decision, an evidence record and a named owner. Each one is mapped one-to-one to the traditional activity it absorbs, so a reader can see that almost nothing here is new; the mechanical part moved to a check, the reading and drafting moved to an agent, and the decision stayed with a person but now carries evidence.</p>
<div class="stats small"><div><b>{len(data['workflows'])}</b><span>workflows</span></div><div><b>{len(data['phases'])}</b><span>phases</span></div><div><b>{counts.get('Floor',0)}</b><span>floor</span></div><div><b>{counts.get('First',0)}</b><span>first</span></div><div><b>{counts.get('Later',0)}</b><span>later</span></div><div><b>{len(data['traditional_map'])}</b><span>traditional activities mapped</span></div></div>
</div></div>
<div class="section-inner">
<div class="catalog-controls">
<div class="viewtabs" role="tablist"><button class="on" data-view="map" role="tab">Map</button><button data-view="table" role="tab">Table</button><button data-view="traditional" role="tab">Traditional map</button></div>
<input id="wf-search" type="search" placeholder="Filter workflows…" aria-label="Filter workflows">
<div class="filterbar" id="wf-maturity"><span class="k">Maturity</span><button class="chipbtn on" data-m="all">All</button><button class="chipbtn m-Floor" data-m="Floor">Floor</button><button class="chipbtn m-First" data-m="First">First</button><button class="chipbtn m-Later" data-m="Later">Later</button></div>
<div class="filterbar" id="wf-applies"><span class="k">Change type</span><button class="chipbtn on" data-a="all">All</button><button class="chipbtn" data-a="UI">UI</button><button class="chipbtn" data-a="API">API</button><button class="chipbtn" data-a="Data">Data</button></div>
</div>
<div class="legend-row"><span class="k">Maturity</span>{''.join(f'<span class="lg m-{k}"><i></i>{k} — {esc(v)}</span>' for k, v in data['maturity'].items())}</div>
<div id="wf-map" class="wf-map" data-view="map"></div>
<div id="wf-table" class="wf-table" data-view="table" hidden></div>
<div id="wf-trad" class="wf-trad" data-view="traditional" hidden></div>
<p class="muted small-note">Sources for the traditional side: {', '.join(esc(v) for v in data['sources'].values())}. No tool names in the catalog by design; tools appear only in the traditional map as they were in the sources. Download the catalog as <a href="data/workflow-catalog.json" download>JSON</a> or <a href="data/workflow-catalog.csv" download>CSV</a>.</p>
</div>
<div class="wf-detail" id="wf-detail" hidden><div class="wf-detail-panel"><button class="lightbox-close" type="button" aria-label="Close">×</button><div class="wf-detail-body"></div></div></div>
</main>
<script id="wf-data" type="application/json">{wf_json}</script>
{glossary_json()}
{footer()}
</body></html>"""
    return page


# --------------------------------------------------------------------------- discovery files
def write_discovery() -> None:
    urls = ["index.html", "workflow-catalog.html", "glossary.html", "references.html"]
    sm = '<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'
    for u in urls:
        loc = f"{SITE_URL}/" if u == "index.html" else f"{SITE_URL}/{u}"
        sm += f"  <url><loc>{loc}</loc><lastmod>{TODAY}</lastmod></url>\n"
    sm += "</urlset>\n"
    write(SITE / "sitemap.xml", sm)
    write(SITE / "robots.txt", f"User-agent: *\nAllow: /\nSitemap: {SITE_URL}/sitemap.xml\n")
    # llms.txt
    lines = [f"# {TITLE}", "", f"> {TOC['tagline']}", "", f"By {TOC['author']}. Edition {VERSION}. Prose CC BY 4.0.", "",
             "## Reference", f"- [The map]({SITE_URL}/): the five bands and the adoption path",
             f"- [SDLC workflow catalog]({SITE_URL}/workflow-catalog.html)", f"- [Terminology and sources]({SITE_URL}/glossary.html)",
             f"- [References]({SITE_URL}/references.html)", f"- [Full text]({SITE_URL}/llms-full.txt)",
             "", f"## The series: {SERIES['title']}", f"{SERIES['summary']} Published at {SERIES_URL}/"]
    for c in PARTS:
        lines.append(f"- [Part {c['number']}: {c['title']}]({part_url(c)}): {c['summary']}")
    write(SITE / "llms.txt", "\n".join(lines) + "\n")
    full = [f"# {TITLE}", "", TOC["tagline"], ""]
    for p in sorted(DIAGRAMS_SVG.glob("*.svg")):
        svg = ET.parse(p).getroot()
        parts = {el.tag.rsplit("}", 1)[-1]: (el.text or "").strip() for el in svg if el.tag.rsplit("}", 1)[-1] in ("title", "desc")}
        if parts.get("title"):
            full += [f"\n\n# {parts['title']}", "", parts.get("desc", "")]
    full += ["\n\n# Terminology", ""]
    for g in GLOSSARY:
        full.append(f"- **{g['term']}** ({g['attribution']}{', source: ' + g['source'] if g.get('source') else ''}): {g['definition'].strip()}")
    full += ["\n\n# References", ""]
    for k, r in REFERENCES.items():
        by = ", ".join(x for x in [r.get("author"), r.get("org")] if x)
        full.append(f"- {r['title']} — {by}. {r['url']}")
    full += ["\n\n# The series", "", f"{SERIES['title']}: {SERIES['summary']} Published at {SERIES_URL}/", ""]
    full += [f"- Part {c['number']}: {c['title']} — {part_url(c)}" for c in PARTS]
    write(SITE / "llms-full.txt", "\n".join(full) + "\n")
    # search index
    idx = []
    for c in PARTS:
        idx.append({"t": f"Part {c['number']}: {c['title']}", "u": part_url(c), "k": "series", "s": c["summary"], "b": c["summary"]})
    for g in GLOSSARY:
        idx.append({"t": g["term"], "u": f"glossary.html#{g['id']}", "k": "term", "s": g["definition"].strip()[:200], "b": g["definition"].strip()})
    for w in CATALOG["workflows"]:
        idx.append({"t": f"{w['id']} {w['name']}", "u": f"workflow-catalog.html#{w['id']}", "k": "workflow", "s": w["decision"], "b": " ".join(str(v) for v in [w["agent"], w["checks"], w["people"], w["traditional"]["activity"]])})
    write(SITE / "search-index.json", json.dumps(idx))
    # data downloads
    (SITE / "data").mkdir(exist_ok=True)
    write(SITE / "data" / "workflow-catalog.json", json.dumps(CATALOG["workflows"], indent=1))
    import csv, io
    buf = io.StringIO()
    wcsv = csv.writer(buf)
    wcsv.writerow(["id", "phase", "name", "decision", "trigger", "agent", "checks", "people", "evidence", "applies_to", "maturity", "traditional_activity", "traditional_owner", "traditional_artefact", "notes"])
    for w in CATALOG["workflows"]:
        wcsv.writerow([w["id"], w["phase"], w["name"], w["decision"], w["trigger"], w["agent"], w["checks"], w["people"], w["evidence"], "; ".join(w["applies_to"]), w["maturity"], w["traditional"]["activity"], w["traditional"]["owner"], w["traditional"]["artefact"], w.get("notes") or ""])
    write(SITE / "data" / "workflow-catalog.csv", buf.getvalue())
    # 404
    set_prefix("")
    page = head(f"Not found · {TITLE}", "Page not found.", "404.html") + "<body>" + nav("") + f'<main><div class="hero hero-plain"><div class="hero-inner"><h1>Not found</h1><p class="lede">That page is not part of this site. <a href="{SITE_URL}/">Start from the map</a>, or read the series at <a href="{esc(SERIES_URL)}/" rel="noopener">{esc(SERIES["title"])}</a>.</p></div></div></main>' + glossary_json() + footer() + "</body></html>"
    write(SITE / "404.html", page)
    write(SITE / ".nojekyll", "")


# --------------------------------------------------------------------------- main
def main() -> None:
    ids = write_diagram_files()
    write(SITE / "index.html", render_index())
    write(SITE / "glossary.html", render_glossary())
    write(SITE / "references.html", render_references())
    write(SITE / "workflow-catalog.html", render_catalog())
    write_discovery()
    print(f"Generated 4 pages, {len(ids)} diagrams → {SITE}")

if __name__ == "__main__":
    main()
